### ISSUE TITLE
2024.10.2 break SS integration stops working

### ISSUE THREAD

**Issue by farberm** [briis/securityspy#101]
Error settup up SecuritySpy

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/securityspy/__init__.py", line 72, in async_setup_entry
    server_info = await securityspyserver.get_server_information()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysecspy/secspy_server.py", line 212, in get_server_information
    return await self._get_server_information()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysecspy/secspy_server.py", line 193, in _get_server_information
    for preset in sched_preset["schedulepreset"]:
                  ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by cbamesberger** [comment]
I got the same issue

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 11:06:32 AM (1 occurrences)
Last logged: 11:06:32 AM

Error setting up entry SecuritySpy for securityspy
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/securityspy/__init__.py", line 72, in async_setup_entry
    server_info = await securityspyserver.get_server_information()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysecspy/secspy_server.py", line 212, in get_server_information
    return await self._get_server_information()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pysecspy/secspy_server.py", line 193, in _get_server_information
    for preset in sched_preset["schedulepreset"]:
                  ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
TypeError: string indices must be integers, not 'str'

**Comment by nzrutman** [comment]
Same.

**Comment by ak-ha-guy** [comment]
Same

**Comment by ak-ha-guy** [comment]
I tried reconfiguring the setup.  I also verified HTTP and 8000 on SS.  No luck 
2024-10-15 09:09:23.251 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Wxxxxx for securityspy

**Comment by nzrutman** [comment]
I rolled back core to 2024.9.2 and SSpy integration is working again.
`ha core update --version 2024.9.2`

**Comment by nzrutman** [comment]
Well, it doesn't seem to be directly broken by core 10.2; I managed to get a dev environment set up and SSpy integration has no problems starting there.
`sched_preset = sys_info.get("schedulepresetlist")` in secspy_server.py is None, which is correctly handled. Somehow this seems not to be the case on my real HA installation; now I need to figure out how to get my debug pysecspy to install there.
FYI if there are others looking for secspy_server.py, it's over at https://github.com/briis/pysecspy

**Comment by nzrutman** [comment]
Tried upgrading to 10.3 on my real system just now, and it seems to be working for the moment. If it fails, my workaround idea to try is adding a fake Schedule Preset in my Security Spy (app) settings (Settings, Scheduling, Schedule Presets).

**Comment by jarrah31** [comment]
10.3 has made the SS integration work again for me.

**Comment by ak-ha-guy** [comment]
Same.  10.3 is working.
