### ISSUE TITLE
Update not work for me..

### ISSUE THREAD

**Issue by leovj** [briis/securityspy#16]
Hi, I have try update the  to version 1.0.0 but my camera not work, i have try to update SecuritySpy to version 5.3.2 but is the same. HA asks me for the data: IP, port, authentication. I put them in but it doesn't seem to work.
Thanks

<img width="1360" alt="Schermata 2021-04-08 alle 10 10 48" src="https://user-images.githubusercontent.com/6884242/113992766-1449fc80-9854-11eb-8104-a7336a456b0f.png">

**Comment by leovj** [comment]
<img width="401" alt="Schermata 2021-04-08 alle 11 19 37" src="https://user-images.githubusercontent.com/6884242/114001650-6a22a280-985c-11eb-9168-38e1c0db5cfd.png">

**Comment by briis** [comment]
Have you enabled the Web Server in SecuritySpy? And defined a user with admin privileges?
If yes, that is then the information you need to put in the box above. Also verify that you run the SecuritySpy Webserver on port 8000. If not change the port number in the box also.

Please read [this section](https://github.com/briis/securityspy#prerequisites) in the README documentation

**Comment by leovj** [comment]
<img width="744" alt="Schermata 2021-04-08 alle 12 14 18" src="https://user-images.githubusercontent.com/6884242/114010196-25026e80-9864-11eb-8817-87e271e30d91.png">
<img width="740" alt="Schermata 2021-04-08 alle 12 14 37" src="https://user-images.githubusercontent.com/6884242/114010218-2a5fb900-9864-11eb-9e9c-6a8ad8cf35b9.png">

**Comment by leovj** [comment]
The strange thing is that with the previous version of the integration everything works (0,1.2) ..

**Comment by briis** [comment]
Could you try and make the Home Assistant user an Administrator - just to check if that changes something?

**Comment by divemasterjm** [comment]
Just for yogur info, every time you open the integration it asks for fill all fields even if is working.

**Comment by maennes** [comment]
Rolling back to 0.1.2 works fine with the same host and account

**Comment by briis** [comment]
Yes I would imagine. But 0.1.2 has no motion events or other event based updates and is completely different from 1.0. After that release I rewrote the whole engine, and 1.0.0 has now been running on one of my machine since it was released, without a single error in the log file.

So it must be something with your local setup, that gives issues. You could try and enable the debug log to see if it gives something useful in the HA log file. Add this to your `configuration.yaml` file:

```yaml
logger:
  default: error
  logs:
    custom_components.securityspy: debug
```
Restart Home Assistant and try again.

**Comment by maennes** [comment]
Thanks for looking into this so promptly!

Here's what I get when installing this integration (v1.0.0):

```
2021-04-08 09:46:52 INFO (SyncWorker_3) [homeassistant.util.package] Attempting install of pysecspy==1.1.1
2021-04-08 09:47:47 DEBUG (MainThread) [custom_components.securityspy.config_flow] Fetching Server Information failed: 404 - Reason: OK
```

**Comment by briis** [comment]
Thanks. It fails on a very basic call to get info on your SecuritySpy setup.
Could you try to do something similar, just manual.

In the following replace
* USERNAME with the SecuritySpy username you use in the Integration
* PASSWORD with the SecuritySpy password you use in the Integration
* IP_ADDRESS with the SecuritySpy server ip address

Open a Webbrowser and type: `http://USERNAME:PASSWORD@IP_ADDRESS:8000/systemInfo`

Let me know if that works.

**Comment by maennes** [comment]
Shouldn't this be a ++systemInfo, because this works:

`curl http://USERNAME:PASSWORD@IP_ADDRESS:8000/++systemInfo`

**Comment by briis** [comment]
On the latest version (5.3.2) of SecuritySpy you don't need the ++ in front anymore.
But doing the curl command is better than the Webbrowser, as the webbrowser will prompt you for credentials again.

**Comment by maennes** [comment]
FFIW, I upgraded from 5.2.2 to 5.3.2 just now, but alas no change during initial setup - still fails albeit with more debug info:
`2021-04-08 10:26:52 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 56, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 74, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 129, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 131, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 155, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 107, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 156, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 214, in _async_handle_step
    result: dict = await getattr(flow, method)(user_input)
  File "/config/custom_components/securityspy/config_flow.py", line 57, in async_step_user
    server_info = await secspy.get_server_information()
  File "/usr/local/lib/python3.8/site-packages/pysecspy/secspy_server.py", line 195, in get_server_information
    return await self._get_server_information()
  File "/usr/local/lib/python3.8/site-packages/pysecspy/secspy_server.py", line 177, in _get_server_information
    for preset in sched_preset["schedulepreset"]:
TypeError: 'NoneType' object is not subscriptable`

**Comment by briis** [comment]
I believe there is now a fix for this:

Could you test it by editing the file `manifest.json` in your `custom_components/securityspy` directory and then change this:

```json
    "requirements": [
        "pysecspy==1.1.1"
    ]
```
to this:

```json
    "requirements": [
        "pysecspy==1.1.2"
    ]
```
then restart Home Assistant and try again.

**Comment by leovj** [comment]
When upload my log viewer say:
    
return await self._get_server_information()
  File "/usr/local/lib/python3.8/site-packages/pysecspy/secspy_server.py", line 177, in _get_server_information
    for preset in sched_preset["schedulepreset"]:
TypeError: 'NoneType' object is not subscriptable

**Comment by maennes** [comment]
Perfect! Changing to pysecspy=1.1.2 worked! A million thanks!

**Comment by leovj** [comment]
YES! Thanks!!

**Comment by briis** [comment]
Glad we found the issue. I will close this now. The fix will officially be implemented in the next release.
