### ISSUE TITLE
Update Home Assistant 2021.9.1

### ISSUE THREAD

**Issue by leovj** [briis/securityspy#24]
Hi I ha ve update Home Assistant to 2021.9.1 but the log say:

`2021-09-03 14:39:54 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 119, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 89, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 24, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 144, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 135, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 590, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 608, in handle
    image = await _async_get_image(
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 169, in _async_get_image
    image_bytes = await camera.async_camera_image()
  File "/config/custom_components/securityspy/camera.py", line 179, in async_camera_image
    last_image = await self.secspy.get_snapshot_image(self._device_id)
  File "/usr/local/lib/python3.9/site-packages/pysecspy/secspy_server.py", line 212, in get_snapshot_image
    raise RequestError(
pysecspy.errors.RequestError: Fetching Snapshot Image failed: 404 - Reason: Not Found
`

**Comment by briis** [comment]
Needs a fix, due to changes in 2021.9. I will work on it.

**Comment by leovj** [comment]
> Needs a fix, due to changes in 2021.9. I will work on it.

Many Thanks!! ;)

**Comment by briis** [comment]
Unfortunately I could not reproduce the error, so I cannot test if the fix works. But could you try and do the following:

To test it out, could you modify the `manifest.json` file in the `custom_components/securityspy` directory and change this line:

```json
"requirements": [
    "pysecspy==1.1.12"
  ],
````
to this:

```json
"requirements": [
    "pysecspy==1.1.13"
  ],
````
Then restart Home Assistant, and let me know if this works.

**Comment by leovj** [comment]
I have pysecspy==1.1.9..

**Comment by briis** [comment]
No problem. Just change that to 1.1.13

**Comment by leovj** [comment]
> No problem. Just change that to 1.1.13

I tried, it seems to be ok! Thanks

**Comment by briis** [comment]
Very good. I will make a new release with that included soon. When that comes out, just update as you normally do.
