### ISSUE TITLE
Security spy motion alerts in Home assistant stoped working

### ISSUE THREAD

**Issue by KasperEdw** [briis/securityspy#31]
I have Security Spy running on a mac mini and it works well.
I have home assistant running on another computer on the same network and mostly the integration works fine. 

However, after a few days, motion alerts stop working. I have a few node-red flows that rely on the motion alerts to show the latest image triggering an alert. 

I have also had a few instances where the SecuritySpy integration lost connection. 

Any ideas on how to troubleshoot this?

Best wishes,
Kasper

**Comment by briis** [comment]
Have you enabled the debug log as explained here: https://github.com/briis/securityspy#enable-debug-logging
Just to see if we get more data to go on.

But in general this is most likely network related in some way. I have had the same setup running for 4 month without any restart and any disconnects. So without more data it is hard to suggest any corrections or even change the code.

**Comment by KasperEdw** [comment]
Thanks. Have set the logger and restarted all. I'll get back when I have data to report.

**Comment by KasperEdw** [comment]
Sorry for the delay, busy week. 
If there is any other data you need, let me know.  
From the log:

This error originated from a custom integration.

Logger: homeassistant.core
Source: custom_components/securityspy/camera.py:177
Integration: SecuritySpy for Home Assistant (documentation, issues)
First occurred: 20:25:34 (73 occurrences)
Last logged: 23:02:51

Error executing service: <ServiceCall camera.snapshot (c:1bc097ebe76fe6da99edfd6f74cef301): filename=Template("/config/www/fasan.png"), entity_id=['camera.network_camera_1']>
Error executing service: <ServiceCall camera.snapshot (c:724b14fe1f196aa5e85036b30958f830): filename=Template("/config/www/fasan.png"), entity_id=['camera.network_camera_1']>
Error executing service: <ServiceCall camera.snapshot (c:8124dff9d3d208eb5e54f0490627a080): filename=Template("/config/www/fasan.png"), entity_id=['camera.network_camera_1']>
Error executing service: <ServiceCall camera.snapshot (c:418bfed2d18d1b772d5890b767da9135): filename=Template("/config/www/fasan.png"), entity_id=['camera.network_camera_1']>
Error executing service: <ServiceCall camera.snapshot (c:882e88079479990d87153acbfc90bfe4): filename=Template("/config/www/fasan.png"), entity_id=['camera.network_camera_1']>
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 986, in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore[return-value]  # noqa
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1056, in create_connection
    raise exceptions[0]
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 1041, in create_connection
    sock = await self._connect_sock(
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 955, in _connect_sock
    await self.sock_connect(sock, address)
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 502, in sock_connect
    return await fut
  File "/usr/local/lib/python3.9/asyncio/selector_events.py", line 537, in _sock_connect_cb
    raise OSError(err, f'Connect call failed {address}')
TimeoutError: [Errno 110] Connect call failed ('192.168.0.107', 8000)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1511, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1530, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 209, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 663, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 896, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 700, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 833, in async_handle_snapshot_service
    image = await camera.async_camera_image()
  File "/config/custom_components/securityspy/camera.py", line 177, in async_camera_image
    last_image = await self.secspy.get_snapshot_image(
  File "/usr/local/lib/python3.9/site-packages/pysecspy/secspy_server.py", line 215, in get_snapshot_image
    response = await self.req.get(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 535, in _request
    conn = await self._connector.connect(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 542, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 907, in _create_connection
    _, proto = await self._create_direct_connection(req, traces, timeout)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1206, in _create_direct_connection
    raise last_exc
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 1175, in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "/usr/local/lib/python3.9/site-packages/aiohttp/connector.py", line 992, in _wrap_create_connection
    raise client_error(req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorError: Cannot connect to host 192.168.0.107:8000 ssl:False [Connect call failed ('192.168.0.107', 8000)]

**Comment by KasperEdw** [comment]
Does this mean the error start with the "Cannot connect to host" in the last line?
If so I have to examine the securityspy installation.

**Comment by briis** [comment]
> Does this mean the error start with the "Cannot connect to host" in the last line?

Correct. For some reason the Integration loses the connection to SecuritySpy, and cannot recover from that. Normally, we can recover a loss in connection but some reason not in your case. I don't have a lot of time to built-in more recovery checks right now, but will work on it when I have the time.

To reestablish the connection, you can go to the Integration page, click the *dots* menu in the lower right corner of SecuritySpy and select *Reload*, that will re-establish the connection if we can reach the SecuritySpy server.

**Comment by KasperEdw** [comment]
Thanks for clearing this up and getting me in the right direction. It's a problem with the disk setup on the Security Spy Mac and moving it to a different USB-port appears to have solved the problem. So I'm closing this issue.

**Comment by markmcg17** [comment]
I also get this regularly and I have Home Assistant in a docker on the same Mac mini that is running security spy. I use a web service to trigger motion detection from SS to Homeassistant as this is reliable where as the integration seems to stop working within 24 hours of a reload. A shame as I think the integration would be more useful.

**Comment by briis** [comment]
> as the integration seems to stop working within 24 hours of a reload.

I don't use SS on a daily basis anymore as I migrated everything to Unifi Protect a while ago. But I will do a test setup, and see if I can capture why it stops working, and see if I can find a fix.

**Comment by briis** [comment]
@markmcg17 Mind sharing the Webservice you use, maybe there are things in there I can use?

**Comment by markmcg17** [comment]
I have figured out my problem, I had "quit and reopen every day at midnight" enabled so the integration did no restart after SS restarted. Not sure if a restart is something that an integration can handle?

**Comment by briis** [comment]
The Event Stream might not be able to handle a break, but I need to test and see if anything can be done about it.

**Comment by markmcg17** [comment]
That will be appreciated
