### ISSUE TITLE
One-way communications only?

### ISSUE THREAD

**Issue by denstech** [briis/securityspy#33]
Hello Bjarne, long term SSpy user but fairly new to HA (coming from OpenHab). Running SSpy with 4 cameras on Macmini and HA is on the new HA Blue unit. Everything is on same LAN. Running ver 1.1.1 of your SSpy integration.
SSpy doesn't seem to talk to HA in all cases but HA can instruct SSpy.
Example-1: Cameras offline are NOT picked up by HA entity 'binary-sensor.cam-online'. I tested all 4 cameras, deliberately taking them offline by disconnecting the ethernet cables. They DO show as offline in SSpy but HA still believes they are all perfectly online! I waited for ages.
Example-2: Setting Continuous capture mode to ON from within the SSpy web interface itself is NOT picked up by HA entity 'switch.cam-record-continuous' nor by the HA 'sensor.cam-continuous recording'. However, if continuous recording is initiated FROM HA with the 'switch' entity, SSPy does respond and start recording. So it seems one-way. HA can talk to/instruct SSpy but things initiating from SSpy are not seen by the entities in HA integration.
Am I missing something obvious? I CAN see the video streams from SSpy in HA ok using Picture Glance cards. I was testing the sensor/switch entities with glance card. Any advice very welcome. Great job btw on producing this integration. Thanks, Denis

**Comment by briis** [comment]
Your setup should work. Very similar to mine, except I run on an iMac 27"

Let us start with versions:
Version of SSpy?
Version of Home Assistant?

Then try and enabling debugging, like described here: https://github.com/briis/securityspy#enable-debug-logging

**Comment by briis** [comment]
One more thing:

Did you add a local user to the Web Interface with Admin rights? Like described in the Prerequisites section of the README file? Without full Admin rights somethings might not work

**Comment by denstech** [comment]
Hello, thanks for your reply.
SSpy ver 5.4.0  HA core 2021.12.10  HA OS 7.2
I am the only Admin user in the system, no other (less powerful) users involved.
I have enabled logging as instructed by copying that yaml code into my config yaml, verified the config and restarted HA.
Sorry for newbie question but where will I be looking to see and read the logs and what will be be looking for..?

**Comment by denstech** [comment]
Sample error logs so far. It complains about not being able to open the RTSP streams BUT all 4 cameras ARE displaying when I use the 'auto' view in the Picture glance card. If I pick the 'live' view in the glance card, the streams DONT show.
Why would any of this affect the binary sensor being aware that any camera has gone offline though?
**Log extract** "2022-01-29 10:41:29 WARNING (SyncWorker_0) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-29 10:41:29 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration securityspy which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy] Creating Service: Enable Schedule Preset
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.binary_sensor] Adding binary sensor entity Motion for Camera Gate cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.binary_sensor] Adding binary sensor entity Online for Camera Gate cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.binary_sensor] Adding binary sensor entity Motion for Camera Linny cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.binary_sensor] Adding binary sensor entity Online for Camera Linny cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.binary_sensor] Adding binary sensor entity Motion for Camera Garage cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.binary_sensor] Adding binary sensor entity Online for Camera Garage cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.binary_sensor] Adding binary sensor entity Motion for Camera Sunroom cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.binary_sensor] Adding binary sensor entity Online for Camera Sunroom cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.sensor] Adding sensor entity Motion Recording for Camera Gate cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.sensor] Adding sensor entity Motion Recording for Camera Linny cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.sensor] Adding sensor entity Motion Recording for Camera Garage cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.sensor] Adding sensor entity Motion Recording for Camera Sunroom cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.sensor] Adding sensor entity Continuous Recording for Camera Gate cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.sensor] Adding sensor entity Continuous Recording for Camera Linny cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.sensor] Adding sensor entity Continuous Recording for Camera Garage cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.sensor] Adding sensor entity Continuous Recording for Camera Sunroom cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.sensor] Adding sensor entity Actions Enabled for Camera Gate cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.sensor] Adding sensor entity Actions Enabled for Camera Linny cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.sensor] Adding sensor entity Actions Enabled for Camera Garage cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.sensor] Adding sensor entity Actions Enabled for Camera Sunroom cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.switch] Adding switch entity Actions for Camera Gate cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.switch] Adding switch entity Actions for Camera Linny cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.switch] Adding switch entity Actions for Camera Garage cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.switch] Adding switch entity Actions for Camera Sunroom cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.switch] Adding switch entity Record Motion for Camera Gate cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.switch] Adding switch entity Record Motion for Camera Linny cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.switch] Adding switch entity Record Motion for Camera Garage cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.switch] Adding switch entity Record Motion for Camera Sunroom cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.switch] Adding switch entity Record Continuous for Camera Gate cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.switch] Adding switch entity Record Continuous for Camera Linny cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.switch] Adding switch entity Record Continuous for Camera Garage cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.switch] Adding switch entity Record Continuous for Camera Sunroom cam
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.camera] Adding Camera Id: 0
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.camera] Adding Camera Id: 1
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.camera] Adding Camera Id: 3
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.camera] Adding Camera Id: 2
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.camera] Creating Service: Set Arm Mode
2022-01-29 10:41:34 DEBUG (MainThread) [custom_components.securityspy.camera] Creating Service: Download Latest Recording
2022-01-29 10:41:35 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:41:35 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:41:35 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:41:35 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:41:45 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:41:45 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:41:45 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:41:45 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:42:05 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:42:06 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:42:06 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:42:06 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:42:35 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:42:36 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:42:36 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:42:36 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:43:16 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:43:16 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:43:16 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:43:16 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:44:06 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:44:06 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:44:06 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:44:06 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:45:06 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:45:06 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:45:06 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:45:06 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:46:16 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:46:16 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:46:16 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:46:16 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:47:36 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:47:36 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:47:36 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:47:36 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:49:06 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:49:06 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:49:06 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:49:06 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:50:46 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:50:46 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:50:46 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:50:46 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:52:36 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:52:36 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:52:36 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:52:36 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:54:36 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:54:36 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:54:36 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****
2022-01-29 10:54:36 ERROR (stream_worker) [homeassistant.components.stream] Error from stream worker: Error opening stream rtsp://192.168.2.2:9701/stream?auth=****"

**Comment by denstech** [comment]
Update:  Took some cameras offline. HA still does not see that happening and there is NO trace of the offline events in the logs.  SSpy shows the cameras in an 'offline' state ok when I login to SSpy from another Mac.  
Very odd. Is SSpy just 'not telling' HA about the status or is HA not registering/hearing the event???

**Comment by briis** [comment]
It seams you are using a different port than 8000 for the Webserver in SSpy. Correct? Are you using the http or https port? 
https is not supported, so if you can enable the http port and use that port number

**Comment by denstech** [comment]
Hi, yes I do use different ports for http and https rather than the default (guessable) ports that SSpy suggests.
I do this for security purposes. YI have both type of port access enabled for SSpy. I'm currenty using https to connect your integration to SSpy. 
Will I have to delete the integration and set it up again? When I go into the config, it seems to have forgotten all the previous settings I used. If I leave the integration there and redo the configuration, will I end up with duplicate entities everywhere? Sorry I'm new to HA.. Thanks again for your time this morning :-)

**Comment by briis** [comment]
No issue with changing the ports, just make sure you use the http port. 

> When I go into the config, it seems to have forgotten all the previous settings I used

Yeah, thats bad programming from my side. Just fill it out again, using the http port this time, and it should reload with the new settings. If not, you will have to delete and add again. (Only in Integrations not in HACS)

Let me know if that changes things

**Comment by denstech** [comment]
Update: reconfigured the integration and disabled the RTSP stream in the configuration. All the stream errors have gone away, but... took a camera offline and it's still not seen by HA.
Also, a ton load of new errors in the log, copied below..

New Log extract:
"This error originated from a custom integration.

Logger: aiohttp.server
Source: custom_components/securityspy/camera.py:177 
Integration: SecuritySpy for Home Assistant (documentation, issues) 
First occurred: 13:04:06 (9 occurrences) 
Last logged: 13:05:46

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 92, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 78, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 181, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 137, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 629, in get
    return await self.handle(request, camera)
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 647, in handle
    image = await _async_get_image(
  File "/usr/src/homeassistant/homeassistant/components/camera/__init__.py", line 166, in _async_get_image
    image_bytes = await camera.async_camera_image(
  File "/config/custom_components/securityspy/camera.py", line 177, in async_camera_image
    last_image = await self.secspy.get_snapshot_image(
  File "/usr/local/lib/python3.9/site-packages/pysecspy/secspy_server.py", line 221, in get_snapshot_image
    raise RequestError(
pysecspy.errors.RequestError: Fetching Snapshot Image failed: 404 - Reason: Not Found"

**Comment by denstech** [comment]
OK ALL OK now!
I decided to delete the integration from the Config Integrations section (not the HACS), added it again, set it up again for http and YES all working now. The earlier approach of just re-inputting the new settings didn't seem to do it. So a clean delete & reset it up.
A brilliant integration, great work and many thanks for your excellent and quick assistance today.
I don't know if it's mentioned in your documentation, but I hadn't seen that requirement to have a http and NOT a https link between them.
ps. who closes this discussion & marks it as solved?
thank you again :-)

**Comment by briis** [comment]
Perfect. I was just about to suggest the "Clean" approach, but even better that you figured it out yourself.
Yes please close the issue. Thanks
