### ISSUE TITLE
Update to HA Core 2024 .1.0.  Kills Security Spy HA automations

### ISSUE THREAD

**Issue by captcurrent** [briis/securityspy#52]
Did the update to Coe 2014.1.0 and all the SS automations have apparentl
![Screenshot 2024-01-04 at 3 05 53 AM](https://github.com/briis/securityspy/assets/67183495/2bbfdc81-8cbf-45fd-bb66-8f9a2374f7ac)
y died while camera view remains

**Comment by briis** [comment]
Could you post what is in the Log file?

**Comment by captcurrent** [comment]
File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/securityspy/binary_sensor.py", line 30, in <module>
@dataclass
^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
return wrap(cls)
^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
return _process_class(cls, init, repr, eq, order, unsafe_hash,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
_init_fn(all_init_fields,
File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'key' follows default argument
2024-01-04 07:52:27.514 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'securityspy.binary_sensor': Platform not found (Exception importing custom_components.securityspy.binary_sensor).
2024-01-04 07:52:27.522 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.securityspy.sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/securityspy/sensor.py", line 29, in <module>
@dataclass
^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
return wrap(cls)
^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
return _process_class(cls, init, repr, eq, order, unsafe_hash,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
_init_fn(all_init_fields,
File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'key' follows default argument
2024-01-04 07:52:27.558 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'securityspy.sensor': Platform not found (Exception importing custom_components.securityspy.sensor).
2024-01-04 07:52:27.564 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.securityspy.switch
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 842, in get_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 859, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/securityspy/switch.py", line 22, in <module>
@dataclass
^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1230, in dataclass
return wrap(cls)
^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1220, in wrap
return _process_class(cls, init, repr, eq, order, unsafe_hash,
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/dataclasses.py", line 1027, in _process_class
_init_fn(all_init_fields,
File "/usr/local/lib/python3.11/dataclasses.py", line 545, in _init_fn
raise TypeError(f'non-default argument {f.name!r} '
TypeError: non-default argument 'key' follows default argument
2024-01-04 07:52:27.601 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'securityspy.switch': Platform not found (Exception importing custom_components.securityspy.switch).
2024-01-04 07:52:28.204 WARNING (MainThread) [homeassistant.helpers.entity] Entity camera.side_door (<class 'custom_components.securityspy.camera.SecuritySpyCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.STREAM: 2>, please create a bug report at https://github.com/briis/securityspy/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-01-04 07:52:28.205 WARNING (MainThread) [homeassistant.helpers.entity] Entity camera.front_of_room (<class 'custom_components.securityspy.camera.SecuritySpyCamera'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <CameraEntityFeature.STREAM: 2>, please create a bug report at https://github.com/briis/securityspy/issues and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-01-04 07:52:28.330 WARNING (MainThread) [homeassistant.components.alarm_control_panel] FORMAT_NUMBER was used from alarmo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.NUMBER instead, please create a bug report at https://github.com/nielsfaber/alarmo/issues
2024-01-04 07:52:28.336 WARNING (MainThread) [homeassistant.components.alarm_control_panel] FORMAT_NUMBER was used from alarmo, this is a deprecated constant which will be removed in HA Core 2025.1. Use CodeFormat.NUMBER instead, please create a bug report at https://github.com/nielsfaber/alarmo/issues
2024-01-04 07:56:45.198 WARNING (Wemo Events Thread) [pywemo.subscribe] Resubscribe error for <Subscription insight "Computer"> (HTTPConnectionPool(host='10.0.1.100', port=49153): Read timed out. (read timeout=10)), will retry in 60s
2024-01-04 08:00:30.355 WARNING (Wemo Events Thread) [pywemo.subscribe] Resubscribe error for <Subscription basicevent "Computer"> (HTTPConnectionPool(host='10.0.1.100', port=49153): Max retries exceeded with url: /upnp/event/basicevent1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fd07dd450>, 'Connection to 10.0.1.100 timed out. (connect timeout=10)'))), will retry in 60s
2024-01-04 08:00:33.498 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=5, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fc228a490>, 'Connection to 10.0.1.100 timed out. (connect timeout=3.0)')': /upnp/control/insight1
2024-01-04 08:00:42.760 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fc23389d0>, 'Connection to 10.0.1.100 timed out. (connect timeout=3.0)')': /upnp/control/insight1
2024-01-04 08:00:51.795 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fd08e0550>, 'Connection to 10.0.1.100 timed out. (connect timeout=3.0)')': /upnp/control/insight1
2024-01-04 08:01:09.670 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fd08df250>, 'Connection to 10.0.1.100 timed out. (connect timeout=3.0)')': /upnp/control/insight1
2024-01-04 08:01:38.271 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fd07de2d0>, 'Connection to 10.0.1.100 timed out. (connect timeout=3.0)')': /upnp/control/insight1
2024-01-04 08:01:40.479 WARNING (Wemo Events Thread) [pywemo.subscribe] Resubscribe error for <Subscription insight "Computer"> (HTTPConnectionPool(host='10.0.1.100', port=49153): Max retries exceeded with url: /upnp/event/insight1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fd08de390>, 'Connection to 10.0.1.100 timed out. (connect timeout=10)'))), will retry in 60s
2024-01-04 08:01:50.585 WARNING (Wemo Events Thread) [pywemo.subscribe] Resubscribe error for <Subscription basicevent "Computer"> (HTTPConnectionPool(host='10.0.1.100', port=49153): Max retries exceeded with url: /upnp/event/basicevent1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fc22da350>, 'Connection to 10.0.1.100 timed out. (connect timeout=10)'))), will retry in 60s
2024-01-04 08:02:00.633 ERROR (Wemo Events Thread) [pywemo.ouimeaux_device] Unable to re-probe wemo <WeMo Insight "Computer"> at 10.0.1.100
2024-01-04 08:02:05.944 ERROR (Wemo Events Thread) [pywemo.ouimeaux_device] Unable to reconnect with Computer
2024-01-04 08:02:29.302 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fc2255110>, 'Connection to 10.0.1.100 timed out. (connect timeout=3.0)')': /upnp/control/insight1
2024-01-04 08:02:34.588 WARNING (SyncWorker_3) [pywemo.ouimeaux_device.api.service] Error communicating with Computer at 10.0.1.100:49153, HTTPException(MaxRetryError("HTTPConnectionPool(host='10.0.1.100', port=49153): Max retries exceeded with url: /upnp/control/insight1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fd08cffd0>, 'Connection to 10.0.1.100 timed out. (connect timeout=3.0)'))")) retry 0
2024-01-04 08:02:45.457 ERROR (SyncWorker_3) [pywemo.ouimeaux_device] Unable to re-probe wemo <WeMo Insight "Computer"> at 10.0.1.100
2024-01-04 08:02:46.213 WARNING (MainThread) [homeassistant.helpers.entity] Entity None (<class 'custom_components.browser_mod.media_player.BrowserModPlayer'>) is using deprecated supported features values which will be removed in HA Core 2025.1. Instead it should use <MediaPlayerEntityFeature.PAUSE|SEEK|VOLUME_SET|VOLUME_MUTE|TURN_ON|TURN_OFF|PLAY_MEDIA|STOP|PLAY|BROWSE_MEDIA: 152463>, please report it to the author of the 'browser_mod' custom integration and reference https://developers.home-assistant.io/blog/2023/12/28/support-feature-magic-numbers-deprecation
2024-01-04 08:02:50.548 ERROR (SyncWorker_3) [pywemo.ouimeaux_device] Unable to reconnect with Computer
2024-01-04 08:02:52.841 WARNING (Wemo Events Thread) [pywemo.subscribe] Resubscribe error for <Subscription insight "Computer"> (HTTPConnectionPool(host='10.0.1.100', port=49153): Max retries exceeded with url: /upnp/event/insight1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fc22fbcd0>, 'Connection to 10.0.1.100 timed out. (connect timeout=10)'))), will retry in 60s
2024-01-04 08:02:53.552 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=5, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fc2255fd0>, 'Connection to 10.0.1.100 timed out. (connect timeout=3.0)')': /upnp/control/insight1
2024-01-04 08:02:59.555 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fc242ecd0>, 'Connection to 10.0.1.100 timed out. (connect timeout=3.0)')': /upnp/control/insight1
2024-01-04 08:03:02.852 ERROR (Wemo Events Thread) [pywemo.ouimeaux_device] Unable to re-probe wemo <WeMo Insight "Computer"> at 10.0.1.100
2024-01-04 08:03:07.929 ERROR (Wemo Events Thread) [pywemo.ouimeaux_device] Unable to reconnect with Computer
2024-01-04 08:03:08.558 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fc242f310>, 'Connection to 10.0.1.100 timed out. (connect timeout=3.0)')': /upnp/control/insight1
2024-01-04 08:03:17.940 WARNING (Wemo Events Thread) [pywemo.subscribe] Resubscribe error for <Subscription basicevent "Computer"> (HTTPConnectionPool(host='10.0.1.100', port=49153): Max retries exceeded with url: /upnp/event/basicevent1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fc3b6a150>, 'Connection to 10.0.1.100 timed out. (connect timeout=10)'))), will retry in 60s
2024-01-04 08:03:23.563 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fcd094c50>, 'Connection to 10.0.1.100 timed out. (connect timeout=3.0)')': /upnp/control/insight1
2024-01-04 08:03:27.951 ERROR (Wemo Events Thread) [pywemo.ouimeaux_device] Unable to re-probe wemo <WeMo Insight "Computer"> at 10.0.1.100
2024-01-04 08:03:50.568 WARNING (SyncWorker_3) [urllib3.connectionpool] Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fc23f8590>, 'Connection to 10.0.1.100 timed out. (connect timeout=3.0)')': /upnp/control/insight1
2024-01-04 08:04:23.707 WARNING (SyncWorker_1) [urllib3.connectionpool] Retrying (Retry(total=5, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x7f9fc2405ad0>, 'Connection to 10.0.1.100 timed out. (connect timeout=3.0)')': /upnp/control/insight1
2024-01-04 08:04:23.893 WARNING (Wemo Events Thread) [pywemo.subscribe] Resubscribe error for <Subscription insight "Computer"> (HTTPConnectionPool(host='10.0.1.100', port=49153): Read timed out. (read timeout=10)), will retry in 60s

**Comment by coasttech** [comment]
Same issue here, let me know if you would like my logs as well.

**Comment by stbrun** [comment]
Same in my installation. Let me know if I can help. Best regards, Stefan Am 05.01.2024 um 03:08 schrieb Jezza ***@***.***>:﻿
Same issue here, let me know if you would like my logs as well.

**Comment by briis** [comment]
Release 1.1.8 should fix these issues. Just released so should show up in HACS soon.

**Comment by captcurrent** [comment]
just did   Thanks working good
