### ISSUE TITLE
switch entity error

### ISSUE THREAD

**Issue by divemasterjm** [briis/securityspy#6]
Logger: homeassistant.components.switch
Source: custom_components/securityspy/data.py:59
Integration: Switch (documentation, issues)
First occurred: 12:44:46 PM (32 occurrences)
Last logged: 1:34:47 PM

securityspy: Error on device update!
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 360, in _async_add_entity
await entity.async_device_update(warning=False)
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 465, in async_device_update
await task
File "/config/custom_components/securityspy/entity.py", line 57, in async_update
await self.secspy_data.async_refresh()
File "/config/custom_components/securityspy/data.py", line 47, in async_refresh
self._async_process_updates(
File "/config/custom_components/securityspy/data.py", line 59, in _async_process_updates
for device_id, data in updates.items():
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by divemasterjm** [comment]
Hi @briis 
Now is working without issues, i've got all switches working
thanks for your help!!!
regards

**Comment by briis** [comment]
Issue #5 is still there, and might cause the system to stop updating, so that needs to be fixed. I do know where the issue lies, but I don't have a quick fix.
But glad that we managed to solve one problem :)

**Comment by divemasterjm** [comment]
i had this problem (issue 5#) tonight, system stopped ((
