### ISSUE TITLE
Cannot unload Integration. Throws error

### ISSUE THREAD

**Issue by briis** [briis/securityspy#8]
When the Integration unloads (Stopping Home Assistant or Reloading the Integration) the below error is thrown:

```log
021-03-26 13:17:52 ERROR (MainThread) [homeassistant.config_entries] Error unloading entry SecuritySpy for securityspy
Traceback (most recent call last):
  File "/usr/local/python/lib/python3.9/site-packages/homeassistant/config_entries.py", line 341, in async_unload
    result = await component.async_unload_entry(hass, self)  # type: ignore
  File "/config/custom_components/securityspy/__init__.py", line 125, in async_unload_entry
    await entry_data["secspy_data"].async_stop()
  File "/config/custom_components/securityspy/data.py", line 42, in async_stop
    await self._secspyserver.async_disconnect_ws()
  File "/usr/local/python/lib/python3.9/site-packages/pysecspy/secspy_server.py", line 128, in async_disconnect_ws
    await self.ws_connection.close()
TypeError: object NoneType can't be used in 'await' expression
``

**Comment by briis** [comment]
Issue has been fixed with pysecspy 1.0.7
